#!/bin/csh -fx


set years = ( "2000", "2010", "2010" )
set ctr=1

foreach case ( b.e21.BHISTsmbb.f09_g17.LE2-1251.020  b.e21.BHISTsmbb.f09_g17.LE2-1231.012 b.e21.BHISTsmbb.f09_g17.LE2-1231.020 ) 

@ ctr ++

set year = $years{$ctr}

echo "year = $year"

set ARCHDIR = /glade/campaign/cesm/collections/CESM2-LE/restarts
set SCRDIR = /glade/scratch/nanr/archive/ENSO-BB/

if  ( -d $ARCHDIR/${case}/rest/${year{$ctr}}-01-01-00000 ) then
      echo "got'em "
     if ! ( -d $SCRDIR/${case}/rest/${year}-01-01-00000 ) then
           mkdir -p $SCRDIR/${case}/rest/${year}-01-01-00000/
           echo "x'fer 'em"
           cp -pR $ARCHDIR/${case}/rest/${year}-01-01-00000/* $SCRDIR/${case}/rest/${year}-01-01-00000/
     endif
else
    echo "missing ${case}/rest/${year}-01-01-00000
endif

end


exit
