#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf-node.llnl.gov - 2019/09/19 13:51:05
# Search URL: https://esgf-node.llnl.gov/esg-search/wget/?distrib=false&dataset_id=input4MIPs.CMIP6.HighResMIP.MOHC.MOHC-HadISST-2-2-0-0-0.seaIce.day.siconc.gn.v20170505|aims3.llnl.gov
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='https://esgf-node.llnl.gov/esg-search/wget/?distrib=false&dataset_id=input4MIPs.CMIP6.HighResMIP.MOHC.MOHC-HadISST-2-2-0-0-0.seaIce.day.siconc.gn.v20170505|aims3.llnl.gov'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19480101-19481231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19480101-19481231.nc' 'SHA256' 'beac34abd000121f30d84acbc12ff7daa33583e81619b344d100924a801b0d30'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19490101-19491231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19490101-19491231.nc' 'SHA256' '8a192f15c7d4185af6ffec4e39466de65be1be1ef869a05840d875e7ae4fac14'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19500101-19501231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19500101-19501231.nc' 'SHA256' '7c2f1fa43a3cfdc7386f642e7555efed9b5598b887bb72d9d1dd7ae090965bf1'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19510101-19511231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19510101-19511231.nc' 'SHA256' 'a1fccce5d2387deeb39af7084feced7d65cf029a04b679f8586a713e3e6fb13d'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19520101-19521231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19520101-19521231.nc' 'SHA256' '7f722aaead736f8d8d8b90fe9d8c9b07cdd108727e0d6c636e69e878bb0d45f7'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19530101-19531231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19530101-19531231.nc' 'SHA256' '5e3ec1b2e940aede1f24eba648671bafbbbbe95fe43c771445d8a02b768093d6'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19540101-19541231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19540101-19541231.nc' 'SHA256' 'bf765688157d55c5f79523340dc49f51c95b2522f61abd01a30013f23ea7af8c'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19550101-19551231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19550101-19551231.nc' 'SHA256' '7fc30ccda278397b6ff05fda8c48e0c1a5b27c2db71f29ddc09f3c9031484c5c'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19560101-19561231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19560101-19561231.nc' 'SHA256' '68c6caf969d79305396ad031847c5ddf07fa1c8ed861a65dd037cda657ed5096'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19570101-19571231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19570101-19571231.nc' 'SHA256' 'd5308ad38e427adb1af070409f37115facef39b80587fb5e0ba91e269a93edf6'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19580101-19581231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19580101-19581231.nc' 'SHA256' 'c0b400c826f5b7fcf84b0cbbfe05f027a31822671a6abb470a49f05e25003c2c'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19590101-19591231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19590101-19591231.nc' 'SHA256' 'f0c2505af3d08b7ffd4856e898dbbdbdd66cc909b8471555388c700c7dd21e12'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19600101-19601231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19600101-19601231.nc' 'SHA256' 'b213387f0482f63dc3fe215485b2b675d639ab0d0794c81ead616d1f61d9183b'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19610101-19611231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19610101-19611231.nc' 'SHA256' 'b9abb75f38f9ec4b0bb3426023f18d00c386d4735d83d66d641c2f86f81f2d94'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19620101-19621231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19620101-19621231.nc' 'SHA256' '402d71074df32f3d3676aa81b8861727c8d9f735d80b23ed5a726b9724c22778'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19630101-19631231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19630101-19631231.nc' 'SHA256' '17c9332738c3b3a7f4e9df954adeae086f59ce0ee9b193f2582868f3912122e9'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19640101-19641231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19640101-19641231.nc' 'SHA256' 'e84c2a6795855d5788073954cb5c5055674ca6e7a75139a6442be10a37d0c9bd'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19650101-19651231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19650101-19651231.nc' 'SHA256' '4e4d5ad2351a775daaa70afee51fed62427e061daf35af165be71ef7dec013a0'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19660101-19661231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19660101-19661231.nc' 'SHA256' '98c121ec13093df8c7b853c7fbd7888cfe3dfcdf1fd1dbbb7f3b79acd318b36b'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19670101-19671231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19670101-19671231.nc' 'SHA256' 'b2406ce66c184227c67114a29b74dad244e1dface91771dacc85d5863345c3f2'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19680101-19681231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19680101-19681231.nc' 'SHA256' 'c97e40f9a420aa2f2982d27dfe4e757fb72aa524f7d541d01e73374658183fe5'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19690101-19691231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19690101-19691231.nc' 'SHA256' '6bbf7c8a4780774d15615bbd43c2a4d0d5143c0a5e6d1ae538a32bd765014608'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19700101-19701231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19700101-19701231.nc' 'SHA256' 'e14ebc5b314c50fc2dd4daf094e141a6cf41ba5c950c8bc7d177b26e44490689'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19710101-19711231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19710101-19711231.nc' 'SHA256' '2a499e983fef7180e9e486a5d5142512423681b0bcc007a30f028331892dccca'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19720101-19721231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19720101-19721231.nc' 'SHA256' 'd1ecba16e691bfd356ead476b0fc854fb45552cd714edfb1601887e9f29fc6af'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19730101-19731231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19730101-19731231.nc' 'SHA256' '06dd2835a8db9d8dc5cb694a5e5710915d0796e96df046815aa90a278547b0ef'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19740101-19741231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19740101-19741231.nc' 'SHA256' 'fae5d4406ef22cae637059b98ed612cdacf498d7d78385d709e6ba6b2b5f2415'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19750101-19751231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19750101-19751231.nc' 'SHA256' '15016b2f3243c3561fa0ea2692536c12fe0674092ca8a269b10693b012c99ef2'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19760101-19761231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19760101-19761231.nc' 'SHA256' 'aa5bfe72b5aae0caf9908ce4e328709ec878c3376f420cec2cda36eb2f45ab8d'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19770101-19771231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19770101-19771231.nc' 'SHA256' '03d9bb80cc5782b68721a91e149656a304025921d9f2d0cf3700b8e525c5d22c'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19780101-19781231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19780101-19781231.nc' 'SHA256' '5a82cc55e16632d6d9b8f22a7650ca360bbced100ab3920136224ac6c1b6daf9'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19790101-19791231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19790101-19791231.nc' 'SHA256' '0da9a2f125f100743a1b68283393976d97b5ede0715fda367ea3469aea26fed8'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19800101-19801231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19800101-19801231.nc' 'SHA256' '0be9f063c306b8268cf471c5e0383a920c028abaf7d839793e8f7cc97669a190'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19810101-19811231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19810101-19811231.nc' 'SHA256' '7241c4901ec5b8232d7ee43b6d65eba6b7cc8ab999010ba8796c8f5b51954075'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19820101-19821231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19820101-19821231.nc' 'SHA256' '4f7aca73e928d5e75a18c68e44dfd5fb497a8ed60e2dfec863b11b02b861d123'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19830101-19831231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19830101-19831231.nc' 'SHA256' '402d02988e2d9014e1d0a1b366527b2fa046b05e4c5c943e82939de74fe3ec9e'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19840101-19841231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19840101-19841231.nc' 'SHA256' '8322f6bb2604b0afacd6cf8186518abbe3c2ac493ccaf2ded773166588d1a4b2'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19850101-19851231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19850101-19851231.nc' 'SHA256' '78f2cdf78581a3c2fbd1c95d108926b1a3bbc57ef136ea8ab477c4347c83deb9'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19860101-19861231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19860101-19861231.nc' 'SHA256' '238d22d33861bccbb365671e5d8f6462221f3ec8b3c6a65b7b9ab76dd18ea7c7'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19870101-19871231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19870101-19871231.nc' 'SHA256' 'e39d03e3e8e531f2da6c60caa35ff23c26db20315733cff6d3f9c5c385a90f54'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19880101-19881231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19880101-19881231.nc' 'SHA256' 'e32432945b94374d48ccc5cf9158efaa4e3dd7e3f25e0a635ff02ce730151240'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19890101-19891231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19890101-19891231.nc' 'SHA256' '408fa815dcdb3d7a53806f14855f664b37bb0b174b3e50ffc40f1f5076d3ad03'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19900101-19901231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19900101-19901231.nc' 'SHA256' 'c435830e58f4b1f25cc5c6e08b5e51e122f0c74faec077a531a3ab7a6caf009a'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19910101-19911231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19910101-19911231.nc' 'SHA256' '38cfd459fb2b0b82f900786ab68bf913ac67ecbcc4215c5cc4dadb425713ee39'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19920101-19921231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19920101-19921231.nc' 'SHA256' '720d95f92ca912c354006ec027d4e2e7f350c892992796f29f880af83541f1ca'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19930101-19931231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19930101-19931231.nc' 'SHA256' 'c89d610a9e5e7d5df12de519a4c2ed618d2625598377992910673293cb3e6956'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19940101-19941231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19940101-19941231.nc' 'SHA256' '62756a05b96377c4ba179f0e10b4206658aebcaf4844f926a48d98a01ee6ac21'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19950101-19951231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19950101-19951231.nc' 'SHA256' '0a387b8aae586acca6a7098de103f474a462eacac5b13aa094345049369eb586'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19960101-19961231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19960101-19961231.nc' 'SHA256' '8003d7984688ec02e654c6859fcc32b3b8290a4f6bb38eb73e69c110e11ddd65'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19970101-19971231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19970101-19971231.nc' 'SHA256' 'c1bb73baa2ff20146a69849fa752747518d82df51a78ac6f561541fd4d10730d'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19980101-19981231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19980101-19981231.nc' 'SHA256' '254627bd779f8f9dd72a129d5df6d46a453940440038751d9bf04e3f848c7e42'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19990101-19991231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_19990101-19991231.nc' 'SHA256' '3c1489cd9ca98abe4ce582eee4ce86227a10fe804ada554e694a6d1c76666ae8'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20000101-20001231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20000101-20001231.nc' 'SHA256' '32eaa5ebba601385424797de66bd98bc9a9f8388657e56a1f68ebfa3a435daa3'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20010101-20011231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20010101-20011231.nc' 'SHA256' 'd359eae2a004410f934307b5c4b327c173255167c1da8354e417f213eba4b6fb'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20020101-20021231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20020101-20021231.nc' 'SHA256' 'd688b7fb6ee7f4728d83fb0edae4daeaf6c4fcd7a28e695c39dd6c5788695d1c'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20030101-20031231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20030101-20031231.nc' 'SHA256' 'a779fb360cf05f48bfd53f3204f6b643e1c5f322e42fb62ee409b3fd364e834b'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20040101-20041231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20040101-20041231.nc' 'SHA256' 'ecb0e4131281e5d1f882f5c2b5292b89f93d08ece7913611541d5d6894aa4d4a'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20050101-20051231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20050101-20051231.nc' 'SHA256' 'fad71f0b8552a6a024af92b6d6d034cd34d867599118929b6e9a94d804ebd39f'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20060101-20061231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20060101-20061231.nc' 'SHA256' '6f811903a074daa99e96f99bb427726a55be0135c7b800e337024a8a1cbc1ac1'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20070101-20071231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20070101-20071231.nc' 'SHA256' 'c45888e77d3e3f6ed5ae8cd47faea962e25da1cd10ecb0e427064ea0ce2a41c8'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20080101-20081231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20080101-20081231.nc' 'SHA256' '20f854d2f3e4b952c26d8b690c3be5ffba39a18cf94851a99a2b43d31381569e'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20090101-20091231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20090101-20091231.nc' 'SHA256' 'c175525fc4991882520d8e0ec8763b9767abe094eedd8e3f3a7e7a194175616a'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20100101-20101231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20100101-20101231.nc' 'SHA256' 'b655d16cdd69e0a5e95ded8afa1a503c745aa9287a5024a36d20c59c8fbe97f5'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20110101-20111231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20110101-20111231.nc' 'SHA256' '641e76e46d38289975d113d1613e1c2cc414977dbd1bce2ca6b91efc00a272d5'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20120101-20121231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20120101-20121231.nc' 'SHA256' '64764cd55f934d3363e96a4848b769aa7edf7352c79313c4485de6ebdfee3982'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20130101-20131231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20130101-20131231.nc' 'SHA256' '710d9a5e10ebd20ba2ebb24a4705018d2a3f61177461f3f1073b87d8cc720f99'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20140101-20141231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20140101-20141231.nc' 'SHA256' '3b24adfe83279233ee15d3845b571e8291111bca12f8f4dd00208956077412d7'
'siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20150101-20151231.nc' 'http://aims3.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6/HighResMIP/MOHC/MOHC-HadISST-2-2-0-0-0/seaIce/day/siconc/gn/v20170505/siconc_input4MIPs_SSTsAndSeaIce_HighResMIP_MOHC-HadISST-2-2-0-0-0_gn_20150101-20151231.nc' 'SHA256' 'afe10b8a9c001ea95f5394dfef81265cf45e05a30d04ef1c43bea47606bfc951'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 68 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
