#!/bin/csh -f
### set env variables

setenv CESMROOT ~cmip6/cesm_tags/release-cesm2.1.2/

set COMPSET = B1850cmip6
set MACHINE = cheyenne
set RESOLN = f09_g17
set mbr = 99

setenv CASENAME b.e21.B1850cmip6.f09_g17.DAMIP-hist-TESTthrids.00${mbr}
setenv REFCASE  b.e21.B1850.f09_g17.CMIP6-piControl.001
setenv RUNROOT  /glade/scratch/nanr/$CASENAME/run/

setenv BASEROOT /glade/scratch/nanr/
setenv CASEROOT /glade/scratch/nanr/$CASENAME
echo --case $BASEROOT$CASENAME --res $RESOLN  --compset $COMPSET 

cd $CESMROOT/cime/scripts/
./create_newcase --case $BASEROOT$CASENAME --res $RESOLN  --compset $COMPSET 

#cd ~/CESM-WF/
#./create_cylc_DAMIP-hist-vlc --case $BASEROOT$CASENAME --res $RESOLN  --compset $COMPSET 

if ($mbr == 99) then
     setenv REFDATE  0841-01-01
endif
if ($mbr == 3) then
     setenv REFDATE  0501-01-01
endif

setenv REFROOT  /glade/p/cesmdata/cseg/inputdata/cesm2_init/b.e21.B1850.f09_g17.CMIP6-piControl.001/${REFDATE}/

echo $CASEROOT
cd $CASEROOT

./xmlchange RUN_REFCASE=$REFCASE
./xmlchange RUN_REFDATE=$REFDATE
./xmlchange RUN_STARTDATE=1850-01-01
#./xmlchange --append CAM_CONFIG_OPTS=-cosp

./xmlchange NTASKS_CPL=1152
./xmlchange NTASKS_ATM=1152
./xmlchange NTASKS_LND=864
./xmlchange NTASKS_ICE=288
./xmlchange NTASKS_OCN=256
./xmlchange NTASKS_ROF=864
./xmlchange NTASKS_GLC=1152
./xmlchange NTASKS_WAV=32
./xmlchange NTHRDS_CPL=1
./xmlchange NTHRDS_ATM=1
./xmlchange NTHRDS_LND=1
./xmlchange NTHRDS_ICE=1
./xmlchange NTHRDS_OCN=1
./xmlchange NTHRDS_ROF=1
./xmlchange NTHRDS_GLC=1
./xmlchange NTHRDS_WAV=1
./xmlchange ROOTPE_ICE=864
./xmlchange ROOTPE_OCN=1152
./xmlchange ROOTPE_WAV=1408

./case.setup


mv user_nl_cam user_nl_cam.`date +%m%d-%H%M`
mv user_nl_clm user_nl_clm.`date +%m%d-%H%M`
mv user_nl_cice user_nl_cice.`date +%m%d-%H%M`
mv user_nl_cpl user_nl_cpl.`date +%m%d-%H%M`

cp /glade/work/nanr/cesm_tags/CASE_tools/cesm2-cmip6/user_nl_files/DAMIP-hist-vlc/hist/user_nl_cam .
cp /glade/work/nanr/cesm_tags/CASE_tools/cesm2-cmip6/user_nl_files/DAMIP-hist-vlc/hist/user_nl_clm .
cp /glade/work/nanr/cesm_tags/CASE_tools/cesm2-cmip6/user_nl_files/DAMIP-hist-vlc/hist/user_nl_cice .
cp /glade/work/nanr/cesm_tags/CASE_tools/cesm2-cmip6/user_nl_files/DAMIP-hist-vlc/hist/user_nl_cpl .

cp $REFROOT/rpointer* $RUNROOT/
ln -s $REFROOT/b.e21* $RUNROOT/

./preview_namelists

qcmd -- ./case.build >& bld.`date +%m%d-%H%M`

