#!/bin/csh -fx
### set env variables

set MACHINE = aleph
set MACHINE = cheyenne
#if ($USER==jedwards)
#set test=test
#else
set test=nanr2
#endif

if ($MACHINE == cheyenne) then
	setenv CESMROOT /glade/work/nanr/cesm_tags/cesm2.1.4-rc.07
	setenv CESM2_LE_TOOLS_ROOT /glade/work/nanr/cesm_tags/CASE_tools/cesm2-le/
	setenv MYROOT /glade/scratch/nanr/aleph/
  	setenv ARCHDIR /glade/scratch/nanr/archive/
  	setenv SCRATCH /glade/scratch/nanr/
else
	setenv CESMROOT /mnt/lustre/share/CESM/cesm2.1.4-rc.07
	setenv CESM2_LE_TOOLS_ROOT $HOME/CESM_CASE_MANAGEMENT_TOOLS
	setenv MYROOT /mnt/lustre/share/CESM
	setenv POSTPROCESS_PATH /home/jedwards/workflow/CESM_postprocessing
	#source $POSTPROCESS_PATH/cesm-env2/bin/activate
  	setenv ARCHDIR /mnt/lustre/share/CESM/archive/
  	setenv SCRATCH /mnt/lustre/share/CESM/output/
endif


set COMPSET = BHISTsmbb
set RESOLN = f09_g17
set RESUBMIT = 0
set STOP_N=1
set STOP_OPTION=nmonths

set smbr =  2
set embr =  2
set REFCASE = b.e21.BHISTsmbb.f09_g17.LE2-1011.001
set REFDATE = 1850-04-01
set REFROOT = /glade/scratch/nanr/archive/${REFCASE}/rest/${REFDATE}-00000/
echo $REFROOT

@ mb = $smbr
@ me = $embr

foreach mbr ( `seq $mb 2 $me` )

if    ($mbr < 10) then
	setenv CASENAME b.e21${test}.${COMPSET}.${RESOLN}.LE2-restart.00${mbr}
else if ($mbr >= 10 && $mbr < 100) then
	setenv CASENAME b.e21${test}.${COMPSET}.${RESOLN}.LE2-restart.0${mbr}
endif

echo $CASENAME

setenv CASEROOT $MYROOT/${test}/$CASENAME
setenv RUNDIR /glade/scratch/nanr/$CASENAME/run

echo $CASEROOT
$CESMROOT/cime/scripts/create_newcase --case $CASEROOT --res $RESOLN  --mach $MACHINE --compset $COMPSET --output-root $SCRATCH
cd $CASEROOT
  
  ./case.setup
  
  ./xmlchange RUN_REFCASE=${REFCASE}
  ./xmlchange RUN_REFDATE=${REFDATE}
  ./xmlchange RUN_STARTDATE=${REFDATE}
  ./xmlchange STOP_N=$STOP_N
  ./xmlchange STOP_OPTION=$STOP_OPTION
  ./xmlchange RESUBMIT=$RESUBMIT
  ./xmlchange DOUT_S_ROOT=$ARCHDIR/$CASENAME
  ./xmlchange GET_REFCASE=FALSE
  ./xmlchange RUN_TYPE=hybrid

  


if ($MACHINE == cheyenne) then
  ./xmlchange NTASKS_ICE=36
  ./xmlchange NTASKS_LND=504
  ./xmlchange ROOTPE_ICE=504
endif

echo " Copy Restarts -------------"
if (! -d $RUNDIR) then
        echo 'mkdir ' $RUNDIR
        mkdir -p $RUNDIR
endif

   cp    ${REFROOT}/rpointer* $RUNDIR/
   ln -s ${REFROOT}/b.e21*.r*    $RUNDIR/

echo " End restarts copy -----------"

  

  ./preview_namelists

  qcmd -- ./case.build >& bld.`date +%m%d-%H%M`
  #$POSTPROCESS_PATH/cesm-env2/bin/create_postprocess --caseroot $CASEROOT 

end             # member loop

exit

