#!/bin/csh -fx
### set env variables

set MACHINE = aleph
set MACHINE = cheyenne
#if ($USER==jedwards)
#set test=test
#else
set test=Ocn
#endif

if ($MACHINE == cheyenne) then
        #setenv CESMROOT /mnt/lustre/share/CESM/cesm2.1.4-exp03
	setenv CESMROOT /glade/work/nanr/cesm_tags/cesm2.1.4-rc.07
	setenv CESM2_LE_TOOLS_ROOT /glade/work/nanr/cesm_tags/CASE_tools/cesm2-le/
	setenv MYROOT /glade/scratch/nanr/aleph/
  	setenv ARCHDIR /glade/scratch/nanr/archive/
  	setenv SCRATCH /glade/scratch/nanr/
else
	setenv CESMROOT /mnt/lustre/share/CESM/cesm2.1.4-rc.07
	setenv CESM2_LE_TOOLS_ROOT $HOME/CESM_CASE_MANAGEMENT_TOOLS
	setenv MYROOT /mnt/lustre/share/CESM
	setenv POSTPROCESS_PATH /home/jedwards/workflow/CESM_postprocessing
	#source $POSTPROCESS_PATH/cesm-env2/bin/activate
  	setenv ARCHDIR /mnt/lustre/share/CESM/archive/
  	setenv SCRATCH /mnt/lustre/share/CESM/output/
endif


set COMPSET = BHISTcmip6
set RESOLN = f09_g17
set RESUBMIT = 0
set STOP_N=1
set STOP_OPTION=nmonths

set smbr =  1
set embr =  1


@ mb = $smbr
@ me = $embr

foreach mbr ( `seq $mb $me` )
set USE_REFDATE = 1231

if    ($mbr < 10) then
	setenv CASENAME b.e21${test}.${COMPSET}.${RESOLN}.LE2-${USE_REFDATE}.00${mbr}
else if ($mbr >= 10 && $mbr < 100) then
	setenv CASENAME b.e21${test}.${COMPSET}.${RESOLN}.LE2-${USE_REFDATE}.0${mbr}
endif

echo $CASENAME
setenv CASEROOT $MYROOT/${test}/$CASENAME
setenv RUNDIR $SCRATCH/$CASENAME/run/
  $CESMROOT/cime/scripts/create_newcase --case $CASEROOT --res $RESOLN  --mach $MACHINE --compset $COMPSET --output-root $SCRATCH
  cd $CASEROOT



echo $CASEROOT
  ./case.setup
  mv user_nl_cam user_nl_cam.`date +%m%d-%H%M`
  mv user_nl_clm user_nl_clm.`date +%m%d-%H%M`
  mv user_nl_cpl user_nl_cpl.`date +%m%d-%H%M`
  mv user_nl_cice user_nl_cice.`date +%m%d-%H%M`
  cp $CESM2_LE_TOOLS_ROOT/user_nl_files/macro-micro-80/user* $CASEROOT/
  cp $CESM2_LE_TOOLS_ROOT/SourceMods/src.pop/BHISTcmip6/* $CASEROOT/SourceMods/src.pop/
  cp $CESM2_LE_TOOLS_ROOT/SourceMods/src.clm/* $CASEROOT/SourceMods/src.clm/
  cp $CESM2_LE_TOOLS_ROOT/SourceMods/src.cam/* $CASEROOT/SourceMods/src.cam/
  
  ./xmlchange RUN_REFCASE=b.e21.B1850.f09_g17.CMIP6-piControl.001
  ./xmlchange RUN_REFDATE=${USE_REFDATE}-01-01
  ./xmlchange STOP_N=$STOP_N
  ./xmlchange STOP_OPTION=$STOP_OPTION
  ./xmlchange RESUBMIT=$RESUBMIT
  ./xmlchange DOUT_S_ROOT=$ARCHDIR/$CASENAME
  ./xmlchange GET_REFCASE=TRUE

if ($MACHINE == cheyenne) then
  ./xmlchange NTASKS_ICE=36
  ./xmlchange NTASKS_LND=504
  ./xmlchange ROOTPE_ICE=504
endif

if (! -d $RUNDIR) then
mkdir -p $RUNDIR
endif

cp /glade/scratch/nanr/archive/b.e21.B1850.f09_g17.CMIP6-piControl.001/rest/1231-01-01-00000/rpointer* $RUNDIR/
ln -s /glade/scratch/nanr/archive/b.e21.B1850.f09_g17.CMIP6-piControl.001/rest/1231-01-01-00000/b.e21* $RUNDIR/

  ./preview_namelists
  ./case.setup --reset; ./case.setup

  qcmd -- ./case.build >& bld.`date +%m%d-%H%M`

end             # member loop

exit

