#!/bin/csh -f

set MACHINE = frontera
set MACHINE = cheyenne


set COMPSET = BHISTC5
set EXPERIMENT = BDP-HR
set RESOLN  = ne120_t12
set TAG     = cesm-ihesp-hires1.0.32

set RESUBMIT = 1
set STOP_OPTION=nmonths
set STOP_N=31

set syr =  1982
set eyr =  1982
@ yb = $syr
@ ye = $eyr

set smbr =  3
set embr =  3

@ mb = $smbr
@ me = $embr

foreach year ( `seq $yb 2  $ye` )
foreach mbr  ( `seq $mb  $me` )

setenv CASE b.e13.${EXPERIMENT}.${RESOLN}.test-${year}-11.00${mbr}
setenv REFCASE b.e13.DP-HR_IC.${RESOLN}.${year}-11.01

if ($MACHINE == frontera) then
	set PATH      = $STOCKYARD
	set RUNDIR    = $SCRATCH/$CASE/run
	set CASEROOT  = $STOCKYARD/frontera/cases/cesm13/$CASE
        set TOOLSROOT = $HOME/CESM_tools/ihesp-tools/
        set REFROOT   = /scratch1/06091/nanr/DP-HR/inputdata/cesm2_init/
else 
	set PATH      = /glade/work/nanr/
	set RUNDIR    = /glade/scratch/nanr/$CASE/run
	setenv CASEROOT /glade/work/nanr/ihesp-HiRes/cases/ne120_t12/$CASE
        set TOOLSROOT = /glade/work/nanr/cesm_tags/CASE_tools/ihesp-tools/
        set REFROOT   = /glade/scratch/nanr/DP-HR/inputdata/cesm2_init/
endif

setenv CESMROOT ${PATH}/cesm_tags/${TAG}/


$CESMROOT/cime/scripts/create_newcase --case $CASEROOT --res $RESOLN  --mach $MACHINE --compset $COMPSET --pecount L --run-unsupported

cd $CASEROOT

if ($MACHINE == frontera) then
	./xmlchange NTASKS_CPL=28840
	./xmlchange NTASKS_ATM=28800
	./xmlchange NTASKS_LND=896
	./xmlchange NTASKS_ICE=27944
	./xmlchange ROOTPE_ICE=896
	./xmlchange NTASKS_OCN=16295
	./xmlchange ROOTPE_OCN=28840
	./xmlchange NTASKS_ROF=896
	./xmlchange NTASKS_GLC=1
	./xmlchange NTASKS_WAV=1
else
	./xmlchange NTASKS_CPL=7200
	./xmlchange NTASKS_ATM=7200
	./xmlchange NTASKS_LND=1200
	./xmlchange NTASKS_ICE=6000
	./xmlchange ROOTPE_ICE=1200
	./xmlchange NTASKS_OCN=2135
	./xmlchange ROOTPE_OCN=7200
	./xmlchange NTASKS_ROF=1200
	./xmlchange NTASKS_GLC=1
	./xmlchange NTASKS_WAV=1
endif


./xmlchange RESUBMIT=$RESUBMIT
./xmlchange STOP_OPTION=$STOP_OPTION
./xmlchange STOP_N=$STOP_N
./xmlchange RUN_TYPE=hybrid
./xmlchange RUN_STARTDATE=${year}-11-01
./xmlchange RUN_REFCASE=${REFCASE}
./xmlchange RUN_REFDATE=${year}-11-01
./xmlchange GET_REFCASE=FALSE
./xmlchange OCN_TRACER_MODULES=""
##./xmlchange --append CAM_CONFIG_OPTS=-cosp

if ($MACHINE == cheyenne) then
        ./xmlchange PROJECT=CESM0021
endif

##cp $TOOLSROOT/user_nl_files/DP-HR/user_nl_cam-COSP-ON $CASEROOT/user_nl_cam
cp $TOOLSROOT/user_nl_files/DP-HR/user_nl_cam $CASEROOT/user_nl_cam
cp $TOOLSROOT/user_nl_files/DP-HR/user_nl_clm $CASEROOT/user_nl_clm
cp $TOOLSROOT/user_nl_files/DP-HR/user_nl_cice $CASEROOT/user_nl_cice
cp $TOOLSROOT/user_nl_files/DP-HR/user_nl_rtm $CASEROOT/user_nl_rtm


cp $TOOLSROOT/SourceMods/src.cice/DP-HR/*  $CASEROOT/SourceMods/src.cice/
cp $TOOLSROOT/SourceMods/src.pop/DP-HR/*  $CASEROOT/SourceMods/src.pop/
cp $TOOLSROOT/SourceMods/src.cam/*F90  $CASEROOT/SourceMods/src.cam/

# =========================
# add pertlim perturbation to micro members 2 .. N 
# =========================
if ($mbr != 1) then
cat >> head.${mbr} << EOF

! add micro-member perturbation
pertlim = ${mbr}.d-14

EOF

mv user_nl_cam tmp.cam
cat head.${mbr} tmp.cam  > user_nl_cam
rm tmp.cam head.${mbr}

endif
# =========================
# END - pertlim 
# =========================
#


echo "================="
echo $REFROOT/$REFCASE/${year}-11-01/
echo "================="

./case.setup

cp    $REFROOT/$REFCASE/${year}-11-01/rpoint* $RUNDIR
ln -s $REFROOT/$REFCASE/${year}-11-01/b.* $RUNDIR

#./case.build
end
end
