#!/bin/csh -fx
### set env variables
setenv CESM2_LE_TOOLS_ROOT /glade/work/nanr/cesm_tags/CASE_tools/cesm2-covid/
setenv CESMROOT /glade/work/nanr/cesm_tags/release-cesm2.1.2/

module load intel/17.0.1
module load python/2.7.16
module load graphviz/2.40.1
module load cylc/7.8.3
module load ncarenv/1.3
module load ncarcompilers/0.5.0
module load mpt/2.19
module load netcdf/4.6.3

setenv POSTPROCESS_PATH /glade/u/home/mickelso/CESM_postprocessing_3/
setenv POSTPROCESS_PATH_GEYSER /glade/u/home/mickelso/CESM_postprocessing_3/

set COMPSET = BSSP245cmip6
set SIMULAT = COVID-ssp245-2019
set MACHINE = cheyenne
set RESOLN = f09_g17
set RESUBMIT = 2
set STOP_N=24
set STOP_OPTION=nmonths
set REST_N=6
set REST_OPTION=nmonths


setenv BASEROOT /glade/work/nanr/CESM2-covid/
setenv BASENAME b.e21.${COMPSET}.${RESOLN}.${SIMULAT}


# .0[01-10]: RUN_REFCASE=b.e21.BSSP245cmip6.f09_g17.COVID-gfed-2015-2018.0[01-10]

set smbr =  11
set embr =  50

@ mb = $smbr
@ me = $embr

@ basembr = 1
@ ctr = 1

foreach mbr ( `seq $mb  $me` )

#  advance reference case every 4th member
@ rmndr = $ctr % 4
echo *** Remainder = $rmndr

if    ($basembr < 10) then
        setenv REFCASE  b.e21.BSSP245cmip6.f09_g17.COVID-gfed-2015-2018.00${basembr}
else if ($basembr >= 10 && $basembr < 100) then
        setenv REFCASE  b.e21.BSSP245cmip6.f09_g17.COVID-gfed-2015-2018.0${basembr}
endif

if    ($mbr < 10) then
	setenv CASENAME b.e21.${COMPSET}.${RESOLN}.${SIMULAT}.00${mbr}
else if ($mbr >= 10 && $mbr < 100) then
	setenv CASENAME b.e21.${COMPSET}.${RESOLN}.${SIMULAT}.0${mbr}
endif

echo ============ mbr = $mbr
echo ============ refcase = $REFCASE
echo ============ casename = $CASENAME

if ($rmndr == 0) then
@ basembr ++
endif
@ ctr ++

# ./case.build >& bld.`date +%m%d-%H%M`
end             # member loop

exit

