#!/bin/csh -fx
### set env variables
setenv CESM2_SF_TOOLS_ROOT /glade/work/cesmsf/cesm_tags/CASE_tools/cesm2-sf/
setenv CESMROOT /glade/work/nanr/cesm_tags/cesm2.1.4-rc.07


set COMPSET = B1850cmip6
set MACHINE = cheyenne
set RESOLN = f09_g17
set RESUBMIT = 54
set STOP_N=3
set STOP_OPTION=nyears
set PROJECT=NCGD0044

setenv SCENARIO AAER
setenv REFDATE  1850-01-01
setenv BASENAME b.e21.${COMPSET}.${RESOLN}.CESM2-SF-${SCENARIO}
setenv BASEROOT /glade/work/cesmsf/CESM2-SF/
setenv REFROOT  /glade/scratch/nanr/archive/b.e21.B1850.f09_g17.CMIP6-piControl.001/rest/
setenv RUNROOT  /glade/scratch/cesmsf/
setenv REFCASE  b.e21.B1850.f09_g17.CMIP6-piControl.001

#cd ~cesmsf/CESM-WF/
#./create_cylc_cesm2-sf-ensemble --case $BASEROOT$BASENAME --res $RESOLN  --compset $COMPSET --project $PROJECT 


# case name counter
set smbr =  16
set embr =  20
set bmbr =  1


@ mb = $smbr
@ me = $embr

# reference name counter
@ mmm = ($bmbr * 2) - 1


foreach mbr ( `seq $mb  $me` )

@ USE_REFDATE = 1111 + ( $mmm - 1 ) * 10
@ mmm+=2

setenv REFDATE  ${USE_REFDATE}

echo $mbr 
echo $REFDATE 

end             # member loop

exit

