#!/bin/bash

#PBS -N tfnud1
#PBS -q regular
#PBS -l select=1:ncpus=36:mpiprocs=36
#PBS -l walltime=12:00:00
#PBS -A P93300313


##########
##
## See https://github.com/NCAR/CESM_postprocessing/wiki for details
## regarding settings for optimal performance for CESM postprocessing tools.
##
##########


today="$(date '+%Y%m%d-%H%M%S')"
log_filename=/glade/work/nanr/L83/f.e21.FHIST_BGC.f09_f09_mg17.L83_cam6_nudging_clim.001/postprocess/logs/timeseries.log.$today

module load singularity/3.7.2
module load impi


mpirun singularity run -B /glade,/var /glade/work/bdobbins/Containers/CESM_Postprocessing/image /opt/ncar/cesm_postprocessing/cesm-env2/bin/cesm_tseries_generator.py  --caseroot /glade/work/nanr/L83/f.e21.FHIST_BGC.f09_f09_mg17.L83_cam6_nudging_clim.001/postprocess >> ${log_filename} 2>&1 

